---
title: "CS 422 Homework 7"
author: "Tania Soutonglang"
output: 
  html_notebook:
  toc: yes
toc_float: yes
---
```{r}
library(keras)
library(dplyr)
library(caret)
library(rpart)
library(rpart.plot)

rm(list=ls())

# Set working directory as needed
setwd("C:\\Users\\tsout\\OneDrive\\Desktop\\cs422\\CS422-labs\\homework7")

df <- read.csv("wifi_localization.csv", header=TRUE, comment="#")

# Seed the PRNG
set.seed(1122)
df <- df[sample(nrow(df)), ] # Shuffle, as all of the data in the .csv file
                             # is ordered by label! 

# Split the data
indx <- sample(1:nrow(df), 0.20*nrow(df))
test.df  <- df[indx, ]
train.df <- df[-indx, ]
```
### 2.1-a
```{r}
model <- rpart(room ~ ., data=train.df, method="class")
rpart.plot(model, extra=104, fallen.leaves=T, type=4, main="1994 U.S. Census")

predictions <- predict(model,test.df,type="class")
confusion.matrix <- confusionMatrix(as.factor(test.df$room), predictions)

paste0("Decision Tree Model")
paste0("Overall Accuracy: ", signif(confusion.matrix[["overall"]][["Accuracy"]], 2))
cat(paste0('Sensitivity Class 1: ', signif(confusion.matrix[["byClass"]][1,1], 2), 
       ' Class 2: ', signif(confusion.matrix[["byClass"]][2,1], 2),
       ' Class 3: ', signif(confusion.matrix[["byClass"]][3,1], 2),
       ' Class 4: ', signif(confusion.matrix[["byClass"]][4,1], 2)))
cat(paste0('\nSpecificity Class 1: ', signif(confusion.matrix[["byClass"]][1,2], 2), 
       ' Class 2: ', signif(confusion.matrix[["byClass"]][2,2], 2),
       ' Class 3: ', signif(confusion.matrix[["byClass"]][3,2], 2),
       ' Class 4: ', signif(confusion.matrix[["byClass"]][4,2], 2)))
cat(paste0('\nPPV Class 1: ', signif(confusion.matrix[["byClass"]][1,3], 2), 
       ' Class 2: ', signif(confusion.matrix[["byClass"]][2,3], 2),
       ' Class 3: ', signif(confusion.matrix[["byClass"]][3,3], 2),
       ' Class 4: ', signif(confusion.matrix[["byClass"]][4,3], 2)))
cat(paste0('\nBal. Acc. Class 1: ', signif(confusion.matrix[["byClass"]][1,11], 2), 
       ' Class 2: ', signif(confusion.matrix[["byClass"]][2,11], 2),
       ' Class 3: ', signif(confusion.matrix[["byClass"]][3,11], 2),
       ' Class 4: ', signif(confusion.matrix[["byClass"]][4,11], 2)))
```
### 2.1-b
```{r}
# Note that in (b) either use a new variable to store the model, or null out
# the variable that stored the model in (a) if you want to reuse that variable.
# The reason is that if you don't null it out, the model in (b) will have
# residual information left over from (a) and your results will not be quite
# accurate.

model.32 <- NULL
begin <- Sys.time()
model.32 <- keras_model_sequential() %>%
  layer_dense(units = 8, activation="relu", input_shape=c(3)) %>%
  layer_dense(units = 4, activation="softmax")

model.32 %>% compile(
  loss = "categorical_crossentropy",
  optimizer="adam",
  metrics=c("accuracy")
)

mode.32 %>% fit(
  data.matrix(train.df_x), 
  train.df_ohe,
  epochs=100,
  batch_size=32,
  validation_split=0.20
)

end <- Sys.time()

runtime <- round(as.numeric(difftime(time1 = end, time2 = begin, units = "secs")), 2)

pred.prob <- predict(model.32, as.matrix(x.test.df))
pred.class <- apply(pred.prob, 1, function(x) which.max(x)-1)
confusion.matrix32 <- confusionMatrix(as.factor(pred.class), as.factor(y.test.df))
```
### 2.1-c
```{r}

```
### 2.1-d
```{r}

```